FROM gradle:8.5-jdk17 AS builder

WORKDIR /app

COPY build.gradle settings.gradle gradlew ./
COPY gradle gradle
RUN chmod +x gradlew

COPY src src

# JAR 빌드
RUN ./gradlew clean build -x test --no-daemon


FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

# 빌드된 JAR 복사
COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

# JAR 실행
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
